#!/bin/bash
cd ~
mkdir fscript
cd fscript
mkdir sc1 sc2 sc3
cd sc1
touch sc1.txt sc2.txt sc3.txt sc3.json sc5.json
mkdir s1 s2 s3
cd ~
mv fscript/sc1/sc1.txt fscript/sc2
mv fscript/sc1/sc5.json fscript/sc2
ls
